### ISSUE TITLE
4) Ejecutar A* - Testing con datos completos

### ISSUE THREAD

**Issue by Fabriexe** [Nano-Nathan/ubae#11]
Desenvolver el codigo obtenido con la totalidad de los datos, para obtener un registro

**Comment by Nano-Nathan** [comment]
Se generarán pares de nodos de manera aleatoria sin repeticiones seleccionando un 10% total para realizar el testing.

Es decir, si el set de datos posee 100.000 nodos, se seleccionarán 10.000 y se relacionarán entre ellos generando 5.000 pares a los cuales se le intentará encontrar el camino óptimo.
